name: My First Workflow
on: workflow_dispatch

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: |
          echo Hi
          echo Goobye
          echo Thanks
